# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areadeinvestigacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Asesor', 'Asesor'), ('Directivo', 'Directivo')], max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Persona')),
                ('grupo_investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeinvestigacion.GrupoInvestigacion')),
            ],
            bases=('persona.persona', models.Model),
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Persona')),
                ('cargo', models.CharField(max_length=50)),
            ],
            bases=('persona.persona', models.Model),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Persona')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeinvestigacion.area')),
            ],
            bases=('persona.persona', models.Model),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
