# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('areadeinvestigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_incripcion', models.DateField()),
                ('correo_alumno', models.CharField(max_length=50, null=True)),
                ('correo_profesor', models.CharField(max_length=50, null=True)),
                ('comentario', models.CharField(max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('nota1', models.FloatField(blank=True, null=True)),
                ('nota2', models.FloatField(blank=True, null=True)),
                ('nota3', models.FloatField(blank=True, null=True)),
                ('nota4', models.FloatField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Estudiante')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeinvestigacion.area')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Asesor')),
            ],
        ),
    ]
