# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20171126_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectogrado',
            options={'verbose_name_plural': 'Proyecto Grado'},
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='nota1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='nota2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='nota3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='nota4',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
